### ISSUE TITLE
v2.3.0 issue with controller:AdminOrders

### ISSUE THREAD

**Issue by MyoDest** [PrestaShop/ganalytics#69]
With the last update there is a huge problem when loading Orders list in BackOffice. With thousands of orders the module creates a lag ranging from 30 to 120 seconds in page load time. Then adding additional load time with every ajax query regarding customers orders. I'm not a developer, just a Prestashop user. If you need additional details regarding this issue, please ask. I had to revert to version 2.2.0 to be able to use my shop.

**Comment by cboillat** [comment]
Hi, exactly the same problem as above. I'm on 1.6.0.9 see file attached. It takes like 1 minute to completely load the page.
![sans titre](https://cloud.githubusercontent.com/assets/1654758/10284716/bd69ee4e-6b85-11e5-8409-4bd3d44a10e2.png)

**Comment by vchon** [comment]
Hello.
Same problem. Thousands of requests on "adminXXX/index.php?controller=AdminGanalyticsAjax&token=[token-xxxxxxxxxxxxxxx]&orderid=[order_id]&customer=[cust_id]".

3 minutes to load a page of orders.

![erreur admin orders](https://cloud.githubusercontent.com/assets/4180643/10602889/5e0442fa-771b-11e5-9e0f-eac5c8503e9d.jpg)
.

**Comment by Quetzacoalt91** [comment]
Hi @vchon,

The issue should be fixed 2.3.1 thanks to #70, did you update your module ?

**Comment by vchon** [comment]
The module is up to date, but I still have the issue.

I have to comment the body of the hook "hookAdminOrder" if I want to use the admin.

![analytics updated](https://cloud.githubusercontent.com/assets/4180643/10603215/1fec198c-771d-11e5-8ac1-441f5b420036.jpg)

(Cache is cleared)

**Comment by Quetzacoalt91** [comment]
Thanks for the report then, we will investigate a new time on this issue.

**Comment by cboillat** [comment]
Hi @vchon,

I had to completely uninstall the module and reinstall it. After that everything was ok.

**Comment by vchon** [comment]
@cboillat Thank you! After updating it did not work. So as you said I re-installed it, and now it works!

**Comment by tucoinfo** [comment]
I confirm, currently a module reinstall is the only way to go on this one.
Issue history: Upgraded to 2.3.1 after upgrading to PS 1.6.1.1

(UNRELATED: If anyone has solved the similar ***spinning puffin of death*** issue when loading the Modules menu please PM me)
